sudo: required
services:
  - docker

before_install:
  - docker build -t orezimeteaching/server -f Dockerfile.dev .

script:
  - docker run orezimeteaching/server npm test -- --coverage

after_sucess:
  #decript environment variables
  - openssl enc -aes256 -d -in .enc -out .env -k $SECRET_KEY
  - openssl enc -aes256 -d -in serviceAccount.json.enc -out serviceAccount.json -k $SERVICE_KEY

  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi

  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud auth activate-service-account --key-file serviceAccount.json
  - gcloud config set project radiant-land-292215
  - gcloud config set compute/zone us-west2-a
  #build production grade dockerfile
  - docker build -t orezimeteaching/server .
  - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_ID" --password-stdin
  - docker push orezimeteaching/server
  - bash ./deploy.sh
